---
# tasks file for clc-provisioning

- name: Create a CenturyLink Cloud group {{ clc_cluster_name }}.{{ server_group }} for the servers
  clc_group:
    name: "{{ clc_cluster_name }}.{{ server_group }}"
    parent: "{{ clc_cluster_name }}"
    location: "{{ datacenter }}"
    state: present

# - name: Do something regarding the network for the servers
#   debug: msg="TODO, for now, we'll use defaults"

- name: Create CLC servers in group {{ clc_cluster_name }}.{{ server_group }}, server count is {{ server_count }}
  clc_server:
    name: "{{ server_group }}"
    location: "{{ datacenter }}"
    template: "{{ server_vm_template }}"
    os_type:  "{{ server_physical_os }}"
    exact_count: "{{ server_count }}"
    count_group: "{{ clc_cluster_name }}.{{ server_group }}"
    group: "{{ clc_cluster_name }}.{{ server_group }}"
    cpu: "{{ server_cpu }}"
    memory: "{{ server_memory }}"
    type: "{{ server_type }}"
    storage_type: "{{ server_storage }}"
    configuration_id: "{{ server_config_id }}"
    additional_disks: "{{ server_additional_disks }}"
  register: clc_servers
  async: "{{ async_time }}"
  poll: "{{ async_poll }}"
#- debug: var=clc_servers

- name: Deploy ssh keys to servers in {{ clc_cluster_name }}.{{ server_group }}
  clc_blueprint_package:
    server_ids: "{{ item.name }}"
    package_id: "{{ ssh_key_package_id }}"
    package_params:
      User: "root"
      SshKey: "{{ lookup('file', '{{ server_cert_store }}/id_rsa.pub') }}"
  with_flattened:
    - clc_servers.servers
  async: "{{ async_time }}"
  poll: "{{ async_poll }}"

- name: Make sure local hosts directory exists
  file:
    name: "{{ ansible_hosts_directory }}"
    state: directory

- name: Write hosts file for {{ clc_cluster_name }}-{{ server_group }}
  template: src="hosts.j2" dest="{{ ansible_hosts_directory }}/hosts-{{ clc_cluster_name }}-{{ server_group }}"
