
- name: check kernel version
  shell: uname -r
  changed_when: False
  register: uname_command

- debug: var=uname_command.stdout

- block:

    - name: Update apt-get dist-upgrade
      apt:
        upgrade: dist
        update_cache: yes

    - name: Update apt-get full upgrade
      apt:
        upgrade: full
        update_cache: yes

    - name: Upgrade the kernel
      apt:
        name: linux-generic-lts-vivid
        install_recommends: yes

    - name: restart machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      sudo: true
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30 timeout=300
      sudo: false

  when: "{{ uname_command.stdout | version_compare('3.19', '<=') }}"
