- name: Add kubelet service configuration.
  template: src=kubelet.conf.j2 dest=/etc/init/kubelet.conf

- name: Enable kubelet service.
  service: name=kubelet enabled=yes

- name: Start kubelet service.
  service: name=kubelet state=restarted
  
- name: Add kube-proxy service configuration.
  template: src=kube-proxy.conf.j2 dest=/etc/init/kube-proxy.conf

- name: Enable kube-proxy service.
  service: name=kube-proxy enabled=yes

- name: Start kube-proxy service.
  service: name=kube-proxy state=restarted
  
