- name: Download kubernetes release.
  get_url:
    url: "{{ kubernetes_url }}"
    dest: /tmp/kubernetes.tar.gz
    force: yes
  register: get_url_request
  until: "'OK' in get_url_request.msg or 'file already exists' == get_url_request.msg"
  retries: 5
  delay: 10

- name: Unarchive kubernetes release.
  unarchive:
    src: /tmp/kubernetes.tar.gz
    dest: /var/lib/
    copy: false
    group: root
    owner: root
    mode: 755

# - name: Unarchive kubernetes release binaries.
#   unarchive:
#     src: /var/lib/kubernetes/server/kubernetes-server-linux-amd64.tar.gz
#     dest: /var/lib/kubernetes/server
#     copy: false
#     group: root
#     owner: root
#     mode: 755

# ansible unarchive seems to be broken on filenames with backslash+tildes, complains
# -->  No such file or directory: '/tmp/kubernetes/addons/gcr.io\\\\\\\\~google_containers\\\\\\\\~kube-registry-proxy:0.3.tar'"
# filenames are created that way when building on OSX :(
- name: Unarchive kubernetes release binaries.
  shell: >
    tar -xzf /var/lib/kubernetes/server/kubernetes-server-linux-amd64.tar.gz
    -C /var/lib/kubernetes/server
    --exclude-tag-under /kubernetes/addons

- name: Create symbolic links to kubernetes binaries.
  file:
    src: "/var/lib/kubernetes/server/kubernetes/server/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    state: link
    mode: 755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubelet
    - kube-proxy
    - kubectl

- name: Create clc config directory
  file:
   path: "/etc/clc/"
   state: directory

- name: Add CLC cloud provider configuration.
  template:
    src: clc.config.j2
    dest: /etc/clc/clc.conf
