- name: Add flanneld service configuration.
  template: src=flanneld.conf.j2 dest=/etc/init/flanneld.conf

- name: Enable flanneld service.
  service: name=flanneld enabled=yes

- name: Start flanneld service.
  service: name=flanneld state=restarted