- name: Add gpg key for docker repository.
  apt_key: keyserver=hkp://pgp.mit.edu:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present
  
- name: Create docker.list file if missing.
  file: path=/etc/apt/sources.list.d/docker.list state=touch
  
#root@CA1WFADK8SM01:~# lsb_release -sd
#Ubuntu 14.04.3 LTS
#root@CA1WFADK8SM01:~# lsb_release -sc
#trusty
#root@CA1WFADK8SM01:~#
  
- name: Add entry ubuntu 14.04.
  lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-trusty main" regexp="(.*).(dockerproject).(.*)"
  
- name: Update installed packages to latest version.
  apt: upgrade=yes

- name: Update packages.
  command: apt-get update

- name: Update installed packages to latest version.
  apt: upgrade=yes

- name: Install docker package.
  apt: name=docker-engine state=present
  
- name: Enable docker service on startup.
  service: name=docker enabled=yes
  
- name: Ensure docker service is started.
  command: service docker restart