---
- name: Get machine resources for etcd
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    - server_parent_group: provisioning_test
    - server_group: etcd
    - datacenter: VA1
    - server_tag: etcd
    - server_count: 1
    - server_memory: 4
    - server_cpu: 1

  pre_tasks:
    - debug: var=server_config_id
    - fail: msg="alas"
      when: False

  roles:
    - clc-provisioning


- name: Get machine resources for k8s master
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    - server_parent_group: provisioning_test
    - server_group: master
    - datacenter: VA1
    - server_tag: master
    - server_count: 1
    - server_memory: 4
    - server_cpu: 1

  pre_tasks:
    - debug: var=server_config_id
    - fail: msg="alas"
      when: False

  roles:
    - clc-provisioning


- name: Get machine resources for k8s minion
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    - server_parent_group: provisioning_test
    - server_group: minion
    - datacenter: VA1
    - server_tag: minion
    - server_count: 1
    - server_memory: 4
    - server_cpu: 2

  roles:
    - clc-provisioning
