---
- name: Check ansible version
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - fail: msg="This playbook requires Ansible 2.0 or greater (found {{ ansible_version.full }})."
      when: "{{ ansible_version|version_compare(2.0,'<') }}"

- name: Get machine resources for k8s minion
  hosts: localhost
  gather_facts: True
  connection: local

  vars:
    - server_storage: 100
    - skip_minion: False
    - async_time: 7200
    - async_poll: 5

  pre_tasks:
    - name: include vars for configuration
      include_vars: "{{ config_vars }}"
      when: config_vars is defined

    - name: include minion-specific vars for configuration
      include_vars: "{{ config_vars_minion }}"
      when: config_vars_minion is defined

    - name: Check for Minion_type
      set_fact:
        server_type: "{{ minion_type }}"
      when: minion_type is defined

    - name: Allocate additional_disks /data space on virtual ("standard") minions
      set_fact:
        server_additional_disks:
          - path: /data
            sizeGB: "{{ server_storage }}"
            type: partitioned
      when: server_type == "standard" and server_storage > 0

    - name: Set Async time differently if type = bareMetal
      set_fact:
        async_time: 14400
        async_poll: 10
      when: server_type == "bareMetal"

  roles:
    - { role: clc-provisioning, when: skip_minion == False }
