---
- name: Check ansible version
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - fail: msg="This playbook requires Ansible 2.0 or greater (found {{ ansible_version.full }})."
      when: "{{ ansible_version|version_compare(2.0,'<') }}"

- name: Get machine resources for etcd
  hosts: localhost
  gather_facts: True
  connection: local
  vars:
    - server_group: etcd
    - datacenter: VA1
    - server_count: 3
    - server_memory: 2
    - server_cpu: 1
    - skip_etcd: False
    - async_time: 7200
    - async_poll: 5

  pre_tasks:
    - name: include vars for configuration
      include_vars: "{{ config_vars }}"
      when: config_vars is defined

    - name: include master-specific vars for configuration
      include_vars: "{{ config_vars_master }}"
      when: config_vars_master is defined

  roles:
    - { role: clc-provisioning, when: skip_etcd == False }
