---
- name: Finalize the ansible inventory file
  hosts: localhost
  gather_facts: False
  connection: local

  tasks:

    - name: set home variable if necessary
      set_fact:
        clc_cluster_home: "{{ lookup('env','HOME') }}/.clc_kube/{{ clc_cluster_name }}"
      when: clc_cluster_home is undefined

    - name: set hosts variable if necessary
      set_fact:
        ansible_hosts_directory: "{{ clc_cluster_home }}/hosts"
      when: ansible_hosts_directory is undefined

    - name: concatenate elements
      assemble:
        src: "{{ ansible_hosts_directory }}"
        regexp: "hosts-.*"
        dest: "{{ ansible_hosts_directory }}/inventory"
        delimiter: "\n###"
