---
- hosts: all
  gather_facts: True

- hosts: localhost
  gather_facts: True
  connection: local

  vars_files:
    - vars.yml

  vars:
    - clc_cluster_name: k8s_cluster
    - cert_dir: "{{ clc_cluster_name }}/k8s_certs"

  tasks:

    - file:
        path: "{{ cert_dir }}"
        state: directory

    - template:
        src: openssl.cnf.j2
        dest: "{{ cert_dir }}/openssl.cnf"

    - template:
        src: openssl-client.cnf.j2
        dest: "{{ cert_dir }}/openssl-client.cnf"

    - name: generate ca cert
      shell: >
        openssl genrsa
        -out "{{ cert_dir }}/ca-key.pem"
        2048

    - shell: >
        openssl req
        -x509
        -sha256
        -new
        -nodes
        -key "{{ cert_dir }}/ca-key.pem"
        -days 10000
        -out "{{ cert_dir }}/ca.pem"
        -subj "/CN=kube-ca"

    #- debug: var=hostvars[item]['ansible_default_ipv4']
    #  with_items: groups['master']

    - name: apiserver-key
      shell: openssl genrsa -out "{{ cert_dir }}/apiserver-key.pem" 2048

    - name: apiserver.csr
      shell: >
        openssl req
        -new
        -sha256
        -key "{{ cert_dir }}/apiserver-key.pem"
        -subj "/CN=kubernetes-master"
        -config "{{ cert_dir }}/openssl.cnf"
        -out "{{ cert_dir }}/apiserver.csr"

    - name: apiserver.pem
      shell: >
        openssl x509 -req
        -sha256
        -in "{{ cert_dir }}/apiserver.csr"
        -CA "{{ cert_dir }}/ca.pem"
        -CAkey "{{ cert_dir }}/ca-key.pem"
        -CAcreateserial
        -days 365
        -extensions v3_req
        -extfile "{{ cert_dir }}/openssl.cnf"
        -out "{{ cert_dir }}/apiserver.pem"


    - name: kubecfg.key
      shell: >
        openssl genrsa
        -out "{{ cert_dir }}/kubecfg.key"
        2048

    - name: kubecfg.csr
      shell: >
        openssl req
        -new
        -key "{{ cert_dir }}/kubecfg.key"
        -out "{{ cert_dir }}/kubecfg.csr"
        -subj "/CN=kubecfg"
        -config "{{ cert_dir }}/openssl-client.cnf"

    - name: kubecfg.pem
      shell: >
        openssl x509 -req
        -in "{{ cert_dir }}/kubecfg.csr"
        -CA "{{ cert_dir }}/ca.pem"
        -CAkey "{{ cert_dir }}/ca-key.pem"
        -CAcreateserial
        -out "{{ cert_dir }}/kubecfg.pem"
        -days 365
        -extensions v3_req
        -extfile "{{ cert_dir }}/openssl-client.cnf"
