
---
- name: Collect Facts
  hosts: all
  gather_facts: True

  tasks:
    - name: Set etcd url to seperate etcd cluster
      set_fact:
        etcd_endpoint: "{% for host in groups['etcd'] %}http://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
      when: etcd_seperate_cluster is defined
    - name: Set etcd url to master server
      set_fact:
        etcd_endpoint: "{% for host in groups['master'] %}http://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
      when: etcd_seperate_cluster is undefined      

- name: Kubernetes Master
  hosts: master
  gather_facts: True
  vars_files:
    - vars.yml
  vars:
    - apiserver_endpoint: http://{{ ansible_default_ipv4.address }}:8080
  pre_tasks:
    - name: set master ip address
      set_fact: master_ip={{ ansible_default_ipv4.address }}
  roles:
    - resolv
    - etcd
    - flannel
    - flannel-network
    - flannel-client
    - kubernetes
    - kubernetes-node
    - kubernetes-master


- hosts: Kubernetes minion
  vars_files:
    - vars.yml
  pre_tasks:
    - set_fact: apiserver_endpoint=http://{{ hostvars[ item ].ansible_default_ipv4.address }}:8080
      with_items: groups['master'][0]

  roles:
    - resolv
    - etcd
    - flannel
    - flannel-client
    - docker
    - docker-flannel
    - kubernetes
    - kubernetes-node

- name: install DNS and UI applications
  hosts: master[0]
  gather_facts: True
  vars_files:
    - vars.yml
  vars:
    - kubernetes_application:
       - skydns
       - kube-ui
    - apiserver_endpoint: http://{{ ansible_default_ipv4.address }}:8080
  roles:
    - kubernetes-application
