---
- name: "Install etcd on group {{ etcd_group }}"
  hosts: "{{ etcd_group }}"
  gather_facts: True
  vars:
    - etcd_install_and_run_service: True

  pre_tasks:

    - name: "Set etcd url for cluster in group {{ etcd_group }}"
      set_fact:
        etcd_endpoint: "{% for host in groups[etcd_group] %}http://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"

  roles:
    - etcd
