---

# Certificates are generated locally, copied out to master and minion
- include: gen_certs.yml

# Provision  master
- name: Kubernetes Master
  hosts: master
  gather_facts: True
  vars_files:
    - vars.yml
  vars:
    # TODO - apiserver_endpoint: https://{{ ansible_default_ipv4.address }}:6443
    - apiserver_endpoint: http://{{ ansible_default_ipv4.address }}:8080
    - clc_cluster_home: "{{ lookup('env','HOME') }}/.clc_kube/{{ clc_cluster_name }}"
    - kube_config_local: "{{ clc_cluster_home }}/kube"

  pre_tasks:
    - name: set master ip address
      set_fact: master_ip={{ ansible_default_ipv4.address }}
    - name: Set etcd url for cluster in group "{{ etcd_group }}"
      set_fact:
        etcd_endpoint: "{% for host in groups[etcd_group] %}http://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
    - name: include vars for master configuration
      include_vars: "{{ config_vars }}"
      when: config_vars is defined

  roles:
    - resolv
    - etcd
    - flannel
    - flannel-network
    - flannel-client
    - kubernetes
    - kubernetes-node
    - kubernetes-master

- name: Save master configuration information to minion_config
  hosts: localhost

  vars:
    - clc_cluster_home: "{{ lookup('env','HOME') }}/.clc_kube/{{ clc_cluster_name }}"

  tasks:
    - name: master_ip -> minion config
      lineinfile:
        dest: "{{ clc_cluster_home }}/config/minion_config.yml"
        line: "master_ip: {{ hostvars[ item ].ansible_default_ipv4.address  }}"
        state: present
        regexp: "^master_ip:"
      with_items: groups["master"][0]


# Provision minion_type
- name: Kubernetes minion
  hosts: minion

  vars_files:
    - vars.yml

  vars:
    - clc_cluster_home: "{{ lookup('env','HOME') }}/.clc_kube/{{ clc_cluster_name }}"

  pre_tasks:

    - name: include vars for minion configuration
      include_vars: "{{ config_vars }}"
      when: config_vars is defined

    - set_fact:
        master_ip: "{{ hostvars[ item ].ansible_default_ipv4.address }}"
      with_items: groups['master'][0]
      when: master_ip is not defined

    # TODO - set_fact: apiserver_endpoint=https://{{ master_ip }}:6443
    - set_fact:
        apiserver_endpoint: "http://{{ master_ip }}:8080"

  roles:
    - resolv
    - etcd
    - flannel
    - flannel-client
    - docker
    - docker-flannel
    - kubernetes
    - kubernetes-node
