---
- name: Collect Facts
  hosts: all
  gather_facts: True

  tasks:
    - name: Set etcd url
      set_fact:
        etcd_endpoint: "{% for host in groups['etcd'] %}http://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"

- hosts: master[0]
  gather_facts: True
  vars_files:
    - vars.yml
  vars:
    - apiserver_endpoint: http://{{ ansible_default_ipv4.address }}:8080
  pre_tasks:
    - name: set master ip address
      set_fact: ip_address={{ ansible_default_ipv4.address }}
  roles:
    - kubernetes-application
