---
- hosts: all
  gather_facts: True


- name: Create certificate authority and certs on localhost
  hosts: localhost
  gather_facts: True
  connection: local

  vars_files:
    - vars.yml

  vars:
    - clc_cluster_name: k8s_cluster
    - cert_dir: "{{ clc_cluster_name }}.d/k8s_certs"

  tasks:

    - name: Read base64 ca cert
      slurp: src="{{ cert_dir }}/ca.crt"
      register: ca_cert
      run_once: true

    - name: Read base64 client key
      slurp: src="{{ cert_dir }}/kubecfg.key"
      register: kubecfg_key
      run_once: true

    - name: Read base64 client cert
      slurp: src="{{ cert_dir }}/kubecfg.crt"
      register: kubecfg_crt
      run_once: true

    - name: Template kubectl config with certificate data
      template:
        src: kube_config.j2
        dest: /etc/kubernetes/kubectl_{{ clc_cluster_name }}_config
