---
- hosts: all
  gather_facts: True

- name: Write kubecfg file
  hosts: localhost
  gather_facts: True
  connection: local

  vars_files:
    - vars.yml

  vars:
    - clc_cluster_name: k8s_cluster
    - cert_dir: "{{ clc_cluster_name }}.d/k8s_certs"
    - cluster_name: "{{ clc_cluster_name }}"
    - namespace: default
    - user_name: admin

  tasks:

    - set_fact: master_ip={{ hostvars[ item ].ansible_default_ipv4.address }}
      with_items: groups['master'][0]

    - name: Read base64 ca cert
      slurp: src="{{ cert_dir }}/ca.crt"
      register: ca_cert_b64
      run_once: true

    - name: Read base64 client key
      slurp: src="{{ cert_dir }}/kubecfg.key"
      register: kubecfg_key_b64
      run_once: true

    - name: Read base64 client cert
      slurp: src="{{ cert_dir }}/kubecfg.crt"
      register: kubecfg_crt_b64
      run_once: true

    - name: Template kubectl config with certificate data
      template:
        src: kube_config.j2
        dest: ./kubectl_{{ clc_cluster_name }}_config


##        #dest: /etc/kubernetes/kubectl_{{ clc_cluster_name }}_config
